BookCase/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookCase.Models
{
    // NOTE: The DataAnnotations are used in migrations and/or in the views
    public class Book
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(13)]
        [MinLength(10)]
        [Display(Name = "ISBN")]
        public string Isbn { get; set; }
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Display(Name = "Genre")]
        public string Genre { get; set; }

        [Required]
        // NOTE: We use the DisplayFormat attribute to prevent displaying the time
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [Display(Name = "Published On")]
        public DateTime PublishDate { get; set; }

        [Required]
        [Display(Name = "Author")]
        public int AuthorId { get; set; }
        [Required]
        [Display(Name = "Author")]
        public Author Author { get; set; }

        [Required]
        public string OwnerId { get; set; }
        [Required]
        public ApplicationUser Owner { get; set; }
    }
}

BookCase/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookCase.Data;
using BookCase.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BookCase.Models.ViewModels;

namespace BookCase.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BooksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);

            var applicationDbContext =
                _context.Book
                        .Include(b => b.Author)
                        .Include(b => b.Owner)
                        .Where(b => b.OwnerId == currentUser.Id);

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public async Task<IActionResult> Create()
        {
            var viewModel = new BookCreateViewModel
            {
                AvailableAuthors = await _context.Author.ToListAsync(),
            };
            return View(viewModel);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookCreateViewModel viewModel)
        {
            // NOTE: Ignore any ModelState errors for a particular property by "removing" it's key
            //       Since we are using a ViewModel, the ModelState Keys 
            //       MUST include the ViewModels' Book property
            ModelState.Remove("Book.Author");
            ModelState.Remove("Book.Owner");
            ModelState.Remove("Book.OwnerId");

            if (ModelState.IsValid)
            {
                var book = viewModel.Book;
                var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                book.OwnerId = currentUser.Id;
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            viewModel.AvailableAuthors = await _context.Author.ToListAsync();
            return View(viewModel);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            var viewModel = new BookEditViewModel
            {
                Book = book,
                AvailableAuthors = await _context.Author.ToListAsync()
            };
            return View(viewModel);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookEditViewModel viewModel)
        {
            var book = viewModel.Book;
            if (id != book.Id)
            {
                return NotFound();
            }

            ModelState.Remove("Book.Author");
            ModelState.Remove("Book.Owner");
            ModelState.Remove("Book.OwnerId");

            if (ModelState.IsValid)
            {
                try
                {
                    var currentUser = await _userManager.GetUserAsync(HttpContext.User);
                    book.OwnerId = currentUser.Id;
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            viewModel.AvailableAuthors = await _context.Author.ToListAsync();
            return View(viewModel);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.Id == id);
        }
    }
}

BookCase/ViewComponents/OtherBooksByAuthorViewComponent.cs
using BookCase.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookCase.ViewComponents
{
    // NOTE: This view component "code-behind" is kinda like the cross between a controller and a razor page code-behind.
    //       The razor view for this component is located in Views/Shared/Components/OtherBooksByAuthor/Default.cshtml
    public class OtherBooksByAuthorViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext _context;

        // NOTE: Use dependency injection to get the Application DB Context
        public OtherBooksByAuthorViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }

        // NOTE: This method is run when the view component is rendered (aka. "invoked")
        //       You can specify any parameters you want, 
        //         as long as you have access to the data when you invoke the view component
        public async Task<IViewComponentResult> InvokeAsync(int authorId, int excludeBookId)
        {
            var otherBooks = await _context.Book
                .Where(b => b.AuthorId == authorId && b.Id != excludeBookId)
                .ToListAsync();

            // NOTE: The razor view is configured to accept an IEnumerable<Book>
            return View(otherBooks);
        }
    }
}

BookCase/Views/Books/Create.cshtml
@model BookCase.Models.ViewModels.BookCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Book.Isbn" class="control-label"></label>
                <input asp-for="Book.Isbn" class="form-control" />
                <span asp-validation-for="Book.Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Genre" class="control-label"></label>
                <input asp-for="Book.Genre" class="form-control" />
                <span asp-validation-for="Book.Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PublishDate" class="control-label"></label>
                <input asp-for="Book.PublishDate" class="form-control" />
                <span asp-validation-for="Book.PublishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.AuthorId" class="control-label"></label>
                <select asp-for="Book.AuthorId" class ="form-control" asp-items="@Model.AuthorOptions"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookCase/Views/Books/Delete.cshtml
@model BookCase.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isbn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookCase/Views/Books/Details.cshtml
@model BookCase.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Isbn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Isbn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.FullName)
        </dd>
    </dl>
</div>
<div>
    @* NOTE: Using a view component. Notice how we pass arguments to the view component *@
    @await  Component.InvokeAsync("OtherBooksByAuthor", new { authorId = Model.AuthorId, excludeBookId = Model.Id})
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookCase/Views/Books/Edit.cshtml
@model BookCase.Models.ViewModels.BookEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Book.Id" />
            <div class="form-group">
                <label asp-for="Book.Isbn" class="control-label"></label>
                <input asp-for="Book.Isbn" class="form-control" />
                <span asp-validation-for="Book.Isbn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Title" class="control-label"></label>
                <input asp-for="Book.Title" class="form-control" />
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.Genre" class="control-label"></label>
                <input asp-for="Book.Genre" class="form-control" />
                <span asp-validation-for="Book.Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.PublishDate" class="control-label"></label>
                <input asp-for="Book.PublishDate" class="form-control" />
                <span asp-validation-for="Book.PublishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Book.AuthorId" class="control-label"></label>
                <select asp-for="Book.AuthorId" class="form-control" asp-items="@Model.AuthorOptions"></select>
                <span asp-validation-for="Book.AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-8">
        @* NOTE: Using a view component. Notice how we pass arguments to the view component *@
        @await  Component.InvokeAsync("OtherBooksByAuthor", new { authorId = Model.Book.AuthorId, excludeBookId = Model.Book.Id})
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookCase/Views/Books/Index.cshtml
@model IEnumerable<BookCase.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Isbn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Isbn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.FullName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>